<?php

$labels['headermini'] = 'Header minimiert';
$labels['hidelabels'] = 'Keine Toolbar-Label';
$labels['hidetoplabels'] = 'Keine Topbar-Label';
$labels['superpreview'] = 'Toggle eMail Ansicht durch Klick auf die Statuszeile der Nachrichtenansicht';
$labels['superpreview_hidefolderslist'] = 'Versteckte Ordner-Liste im erweiterten eMail-Ansicht-Modus';
$labels['unselectable'] = 'Keine Selektion von grafischen Elementen';
