<?php

$labels['headermini'] = 'Minimiser l\'en-tête';
$labels['hidelabels'] = 'Masquer les libellés de la barre d\'outils';
$labels['hidetoplabels'] = 'Masquer les libellés de l\'en-tête';
$labels['superpreview'] = 'Étendre/réduire le panneau d\'aperçu en cliquant sur la barre d\'état des messages';
$labels['superpreview_hidefolderslist'] = 'Masquer la liste des dossiers en mode aperçu étendu';
$labels['unselectable'] = 'Empêcher de sélectionner les éléments de l\'interface';
